spring:
  application:
    name: board

  datasource:
#    url: jdbc:mysql://183.111.242.55:3306/jhl9812181?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/jhl9812181?useSSL=false&serverTimezone=UTC

    password: lee2863!
    username: jhl9812181
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
